default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Qwerty#1
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: promodescuentos

test:
  <<: *default
  database: promodescuentos

production:
  <<: *default
  database: promodescuentos

